packages:
  - "."

allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false
  workerd: false

patchedDependencies:
  '@applemusic-like-lyrics/core': patches/@applemusic-like-lyrics__core.patch
